bt_navigator:
  ros__parameters:
    enable_groot_monitoring: true
    groot_server_port: 5555
    use_sim_time: True
    global_frame: map
    robot_base_frame: beetlebot
    odom_topic: beetlebot/odom
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: "/home/kronton/kronton_ws/src/beetlebot-navigation/beetlebot_navigation/behavior_tree/simple_nav_w_replanning.xml"
